### ISSUE TITLE
cross-seed sometimes injects paused torrents with qbittorrent

### ISSUE THREAD

**Issue by KyleSanderson** [cross-seed/cross-seed#249]
I'm seeing on multiple injections that some are paused with a progress of 0. Forcing a rehash completes to 100%, and then I've been manually starting them. This is not on all torrents.

I'm thinking it's https://github.com/mmgoodnow/cross-seed/blob/c1b23d5dc07115de94f67730bb02e6dd98e7c03f/src/clients/QBittorrent.ts#L280 failing but I don't know for certain.

**Comment by KyleSanderson** [comment]
I'm still seeing this on v4. It really seems to be related to content layout.

**Comment by mmgoodnow** [comment]
I think qBittorrent fixed the bug that made me have to inject torrents paused and then recheck, so I might just be able to remove that workaround to get everything working again.

**Comment by mmgoodnow** [comment]
the one thing is that I don't know if the version that has the fix is accepted by PTs yet, or maybe it has other problems…I've heard recommendations not to use the latest version recently

**Comment by KyleSanderson** [comment]
I'm on qBit 4.4.3 if that helps? I was seeing the behaviour on 4.3.9 as well as 4.4.2

**Comment by mmgoodnow** [comment]
Looks like the bug got fixed in 4.4.3 according to https://github.com/qbittorrent/qBittorrent/discussions/16616. Given that people (on PTs especially) are slow to update their clients, I'd probably want to either do a version check or just wait a while before removing the workaround. Realistically, though, it'll take me a while to get to a potential version check-based fix because I want to get v4 released and then a big docs overhaul done, so I'll likely just wait. If you want to fork and just remove the branches under `shouldManuallyEnforceContentLayout` (except you'll also want to make sure you're still setting the contentLayout in the formdata), it'll probably work for you.

**Comment by KyleSanderson** [comment]
I'm definitely seeing this still on 4.4.3

**Comment by KyleSanderson** [comment]
Yeah - v4.0.1 cross-seed still has the issue with qBittorrent 4.4.3

**Comment by mmgoodnow** [comment]
I haven't tried to fix it yet. Hang tight

**Comment by KyleSanderson** [comment]
No problem. Not sure if you want a new issue for this one or not. I have auto-removal rules in qbittorrent, and it's deleting the data as expected. cross-seed is then seeing the data-less torrents, and re-adding them. Some are getting missing files as expected, I'm suspecting this is the same bug that's actually starting the downloads on these costing hundreds of GBs.

![image](https://user-images.githubusercontent.com/1184902/173176220-4d40ab7b-b6a0-4939-97e8-c0d413d7479d.png)

If there's anything I can do to help stop the bleeding I'm here.

**Comment by KyleSanderson** [comment]
Still seeing the paused injections on cross-seed 4.1.0.

**Comment by mmgoodnow** [comment]
Hm, missed your last comment. When in the lifecycle does the removal happen?

**Comment by KyleSanderson** [comment]
Is there anything more I can do to help.

**Comment by mmgoodnow** [comment]
this is fixed in the above PR. I'll likely hold off on merging it into master for some time as I still want to hear that qBittorrent 4.4 is stable now.
