### ISSUE TITLE
Handling different torrent names on trackers

### ISSUE THREAD

**Issue by manz4rk** [cross-seed/cross-seed#329]
Hi there!

I recently joined a new tracker, and I've put the cross-seed to use. To my surprise, cross-seed did not find any torrent available for cross-seeding, even though I could see them on the listed torrents page.
The only difference was that if the original release was named (for example):
`The.Very.Cool.Show.S01E01.And.A.Nice.Episode.Title.1080p.WEB-DL.DDP5.1.x264-GR0UP`
On this tracker it was listed as:
`The Very Cool Show S01E01 And A Nice Episode Title 1080p WEB DL DDP5 1 H 264 GR0UP`

So dots and dashes have become spaces, x264 was changed to H 264 (or H.264) but the file was exactly the same, and it was listen in the description/NFO. Don't know why this particular tracker would name all the releases this way, but it prevents cross-seed to catch them properly.

This also becomes problematic if the torrent names have been altered (looking at you, eztv). If there's a [eztv.re] at the end of the torrent name and the files in both versions are exactly the same (be it packed or unpacked) – cross-seed does not find them.

Is there any logic in place to remedy that?

**Comment by newadventure079** [comment]
This tool should handle spaces, dots, dashes, etc but wont take into account nfo files and the such.  I think there's an option to allow some variance of size and I think @mmgoodnow talked about making it a bit more flexible regarding folder structure and such.  Basically, look thru the existing issues here (open and closed) and you'll find people already discussing what you're seeing

**Comment by manz4rk** [comment]
Oh, absolutely; I imagine handling NFOs in addition to everything would be a pain, so it's outside the scope – and righfully so. It's just the naming conventions to catch all possible cross-seeds.
Thanks!

**Comment by mmgoodnow** [comment]
a few things:

1. you can check what's causing the rejections in the verbose logs. There are no checks for the name a torrent was listed as on the indexer, but there is a check for the file trees. My guess is that it's getting caught up there, and that there actually _is_ a difference in the file/folder names, which means that we'd need to open the can of worms that is renaming files in your torrent client in order for the cross-seeding to work. 

2. cross-seed will generally not work as well with public trackers due to many common repackaging and renaming practices. It was designed primarily for private trackers, which have more strict naming conventions and enable tools like this to exist.

All that said, @akesher123 has been working on this in #300
