### ISSUE TITLE
general setup issues

### ISSUE THREAD

**Issue by goffy59** [cross-seed/cross-seed#364]
Hello, I am not the most experienced docker user but  I do have about 10 containers (pretty much all your typical servarr related stuff/etc.) I feel like I am going about this all wrong. Taking things I learned from those containers to this. I do not really use docker-compose often except for with a couple apps but the rest of them look like this or similar:

docker run -d \
--name=flaresolverr \
-p 8191:8191 \
-e LOG_LEVEL=info \
--restart=always \
ghcr.io/flaresolverr/flaresolverr:latest

Taking this as inspiration I made this which isn't working correctly(or is working and I am just not using the container correctly):

docker run -d \
--name=cross-seed \
-e PGID=1000 -e PUID=1000 \
-v /home/docker/cross-seed/config:/config \
-v (redacted)/downloads:/torrents \
-v (redacted)cross-seed/:/cross-seeds \
-p 2468:2468 \
crossseed/cross-seed

Based on what I learned from your getting started I tried to run this:

cross-seed search --torrent-dir (redacted)/publictorrent/ --output-dir (redacted)/cross-seed/ --torznab (redacted)/prowlarr/1/api?apikey=(redacted)

but get command not found so I then tried to exec -it into the docker container but its not running even if I start it and try to get into the base of the container it still wont work. I feel like I am missing something completely here and being kind of dumb. I was hoping someone could lead the guy to water so I can attempt to fish and maybe even help me bate my line to catch said fish. All metaphors aside I am just kind of stuck. I have also tried using docker-compose.

version: "2.1"
services:
    cross-seed:
        image: crossseed/cross-seed
        container_name: cross-seed
        user: 1000:1000 # optional but recommended
        ports:
            - "2468:2468" # you'll need this if your torrent client runs outside of Docker
        volumes:
            - /home/docker/cross-seed:/config
            - (redacted)/downloads:/torrents:ro # note that this volume can and should be mounted read-only
            -(redacted)/cross-seed:/output
        command: daemon # this enables the daemon
        restart: unless-stopped

In both instances of container creation they work.. using run -d or docker-compose... but still not sure how to engage with this container.

I am just lost on this. I was hoping for some pointers. Where do I run the command, how am I supposed to interact with this container? Examples would be amazing besides the ones on the wiki itself which I have looked at but I am not getting them.

Anything would help. I am sorry to open an issue like this but I could not find anything on reddit or other tutorials.

I am testing on my public container first then if I can see some functionality to work with I will apply this to my privatetorrent container which is the final destination for this cross-seed solution. Logs of the container seem to indicate running commands of this script but I cant engage with them. Like the help menu and such.

Thanks,

-goffy59

**Comment by spyhuntergenral** [comment]
Just gone through and had a go at setting this up, I'm with you on the documentation, very confusing. non the less got mine going, using docker run

I'll walk you through my thoughts: (I'm no expert) but i think the issue is just how the app expects to be run and how docker starts containers, in the Dockerfile the ENTRYPOINT env is set top ["cross-seed"] and as per the documentation this is how the app is started, but without handy access to the container cli when running a container in dettached mode you would never see anything,

this leaves the container continually restarting itself, you can see this happening by running 'docker logs cross-seed'

with this in mind, as per the wiki we need to pass the `daemon` flag to the cross-seed cmd in the container.
!!!this is not to be confused with the `docker run -d` flag, which runs the container in detached mode.

one way to pass arguments to container commands like this:

`docker run -d [options] <container> <arguments>`

here is my full working run cmd:

```
docker run -d \
--name=cross-seed \
--restart=unless-stopped \
-v /host/path/config:/config \
-v /host/path/to/torrent/sessions:/torrents:ro \
-v /host/path/downloads:/cross-seeds \
-e PGID=1000 -e PUID=1000 \
-p 2468:2468 \
crossseed/cross-seed daemon #note the daemon right on the end...
```


for future reference you can use `docker run -it`  instead of -d which will run the container in your terminal session, this helps a lot when troubleshooting as you can see what the container is getting up to, also don't forget about the `docker logs` command

also once the container is running you can interact with them by using the `docker exec` command, i suggest googling this

Hope this helps @goffy59 :)

**Comment by goffy59** [comment]
Thank you so much!! I feel stupid for missing that in the documentation but now I have something to work with. I still have a bit to go before its setup but this is something I can work with. I am curious, can you show me what your config looks like? I am using qbittorrent and prowlarr but I have two separate containers for public and private torrents. I need to find a way to basically just cross-seed the private torrents. I had a config going but it kept throwing errors so I started over. Thanks again for the help! :)
