### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by kyxap** [cross-seed/cross-seed#428]
n/a

**Comment by BaukeZwart** [comment]
`127.0.0.1` won't work when running a container.
Try `Host_IP:9117`

**Comment by kyxap** [comment]
tried dns name and host ip, same exception

```
**cross-seed  | warn: Failed to reach http://192.168.100.10:9117/api/v2.0/indexers/torrentleech/results/torznab/api
cross-seed  | error: no working indexers available**
```

**Comment by Xiseous** [comment]
Going to add to this since I have the same issue with Prowlarr [Running in Docker]
`docker compose up
[+] Building 0.0s (0/0)
[+] Running 1/0
 ✔ Container cross-seed  Created                                                                                   0.0s
Attaching to cross-seed
cross-seed  | Configuration file already exists.
cross-seed  | info: Validating your configuration...
cross-seed  | error: no working indexers available
cross-seed exited with code 1`

Config.js
`   torznab: [
        "http://192.168.1.7:9696/10/api?apikey=KEYWASHERE",
        "http://192.168.1.7:9696/11/api?apikey=KEYWASHERE"
    ],`
