### ISSUE TITLE
Torrent dir /torrents is invalid [Unraid]

### ISSUE THREAD

**Issue by Greatdane** [cross-seed/cross-seed#529]
I keep getting `Torrent dir /torrents is invalid` error when attempting a new setup on Unraid. 

I got the app from the community apps and followed https://www.cross-seed.org/docs/tutorials/unraid

Screenshot of config file;

<img width="1282" alt="Screenshot 2023-10-25 at 14 05 09" src="https://github.com/cross-seed/cross-seed/assets/5075840/b3e8a1da-6acf-4cdb-89c4-3c5dae0b11b6">

Current is my valid QBitorrent torrent dir `/mnt/user/appdata/qbittorrentvpn/qBittorrent/data/BT_backup/` (set to read only)

The only thing I changed in the config was the `torznab` settings. 

Docker app starts then closed, logs just show;

```
info: cross-seed v5.5.4
info: Validating your configuration...
error: Torrent dir /torrents is invalid
```

**Comment by zakkarry** [comment]
You changed the mount in "Input" from /torrents to /media....and are mounting it as if input was a dataDirs

You would need to add a path (bottom, show more, add a path with those settings) to enable the data based matching I think you are going for Instead of changing Input to /media and what would be your dataDirs settings.

You need to either change input back to /torrents and its host path to your BT_Backup, or add another path and add the /torrents container path and BT_Backup host path setup.

Currently there is no /torrents directory, or mount, for BT_Backup, which is what makes /torrents invalid, and this is required in torrentsDir to function.

**Comment by zakkarry** [comment]
https://www.cross-seed.org/docs/tutorials/unraid#volume-mappings

**Comment by Greatdane** [comment]
Thanks! Looks like I messed up trying to set up data-based-matching. 

I added back /torrents and it worked.

Now trying to fix data-based-matching!
