### ISSUE TITLE
Prowlarr spamming push notifications due to cross-seed activity

### ISSUE THREAD

**Issue by austinarchibald** [cross-seed/cross-seed#541]
I set up cross-seed and I'm getting spammed (looks like about 10 for every single torrent that cross-seed is looking up). I have push notifications set up for a "On Release Grab" within Prowlarr's settings, which has worked perfectly before I set up cross-seed. Is there a way to keep the Release Grab notifications but ignore all the cross-seed activity? Also, it's cluttering my prowlarr history - any way to prevent that as well?

Thank you, this tool is incredible!

**Comment by zakkarry** [comment]
cross-seed has to download torrent files from the tracker to compare and verify accuracy of potential matches. This is the only way to know the contents of the torrent file.

Without grabbing it, we wont know the file tree (names/folders/etc) or any details beyond entire torrent general size and name of the release on the tracker. 

Because of that, grabbing the .torrent file for matches is necessary.

I would suggest maybe you move your notifications away from prowlarr and onto your torrent client, or better still, radarr and sonarr if you use those.

**Comment by austinarchibald** [comment]
Ok, makes sense. I will move the notifications off prowlarr, it's worth it to keep cross-seed. Thanks!
