### ISSUE TITLE
README and a tutorial is missing information about torznab link

### ISSUE THREAD

**Issue by slrslr** [cross-seed/cross-seed#603]
As a newbie torrent client user, it is not easy for me to understand how this software works.

The README.md is missing an example of the app usage cases to give layman idea how he can use it and what it will do.

When I check https://www.cross-seed.org/docs/basics/getting-started it also does not clear this and FAQ page https://www.cross-seed.org/docs/basics/faq-troubleshooting shows mainly some hard to understand technicals.

Back to https://www.cross-seed.org/docs/basics/getting-started I am stuck at "--torznab https://localhost/prowlarr/1/api?apikey=12345" the tutorial does not explain on any nearby place what "torznab link" means, how much it cost, where to get it. Where to get the key number.

Hopefully you will improve this.

**Comment by zakkarry** [comment]
https://www.cross-seed.org/docs/basics/options#torznab

**Comment by slrslr** [comment]
Thumb down for showing weakness and insufficient of yours provided information. Ignorant.

**Comment by zakkarry** [comment]
> Thumb down for showing weakness and insufficient of yours provided information. Ignorant.

Showing weakness? Ignorance? Technically, you're the one who is being ignorant and thus why you are asking for help. The issue is this is covered in the documentation already. I linked you to it, you just chose to not read.

1. what "torznab link" means and where to get it
https://i.imgur.com/PwP2Uul.png

2. How much it costs - it doesn't cost anything. I have no idea what possessed you to ask this question, or where you got the impression that a link to/from software you run somehow costs you money.

3. Where to get the key number? This is in your Prowlarr or Jackett....like the Torznab link is, but you can once again follow the instructions we ALREADY PROVIDE to get this, and subsequently, any additional problems or confusion on the instructions you have are covered in Prowlarr or Jackett's documentation. We don't need to duplicate information already available on official channels, or part of the workflow we describe, in our documentation (Copying the RSS URL).

I don't know what you're expecting, but everything is covered. Thousands of people use these instructions and documentations and I actively maintain it as new things arrive. I'm sorry if you feel it doesn't work for someone completely new to torrenting, but perhaps that's your ignorance and not mine. I've gotten loads of praise for the documentation since I took it over. If you need further explanation google can provide you specifications for the Torznab protocol and in-depth details...

With your attitude, though, I'm not particularly of the mind to continue this conversation. Good luck.
