### ISSUE TITLE
Use subcategories in qBittorrent for new link style

### ISSUE THREAD

**Issue by ShanaryS** [cross-seed/cross-seed#620]
The new style of linking to tracker subdirs in linkDir can leverage the use of subcategories. I've tested this on 4.6.2 and 4.5.3 but this is supported on all versions. However only 4.6.x displays it correctly in the WebUI. Previous versions essentially treat it like separate categories.

https://github.com/cross-seed/cross-seed/blob/d28a977e4402942d3e82ffd0bdcb0e814f87c78a/src/clients/QBittorrent.ts#L301-L308

Only change required is:
`category: legacyLinking ? dataCategory : ${dataCategory}/${tracker}`

qBittorrent will automatically create the categories if they don't exist.

Considering this is only a visual clutter issue on older versions if they disable legacyLinking, I think it would be worth it to implement now rather than later.

**Comment by zakkarry** [comment]
My understanding is that the WebUI doesn't support subcats at all in <4.6.x qbittorrent, meaning I'm not sure this is actually utilizing subcats and not just a path with a forward slash in it.

Also, because of this it would require duplicateCategories to be made in category.cross-seed/tracker I believe....

AutoTMM is a huge hassle.

**Comment by ShanaryS** [comment]
Using new system for tagging torrents.

**Comment by NLZ** [comment]
Subcategories are just a visual feature to translate categories with `/` to a tree view on the UI.
This can be tested by creating a subcategory via the UI and then turning the settings off.
![image](https://github.com/user-attachments/assets/914e358d-fb7e-4c95-8117-9bd4c0fb8e41) ![image](https://github.com/user-attachments/assets/66b0c52e-1f03-4877-af10-43e5058f7835)

But the subcategory settings doesn't need to be enabled, a `/` in category is creating a subfolder with AutoTMM even in earlier versions, I just tested 4.3.9:
![image](https://github.com/user-attachments/assets/b7890ecb-a40d-4fd1-afbb-fd7e1fe9ca77)
It's working at least since 2016 https://github.com/qbittorrent/qBittorrent/issues/5995

AutoTMM's only issue is that it moves files even when multiple torrents are pointing at the same file (from flat cross-seed linking) killing the other torrents, but with v6 this weakness is worked around.

**Comment by zakkarry** [comment]
> But the subcategory settings doesn't need to be enabled, a `/` in category is creating a subfolder with AutoTMM even in earlier versions, I just tested 4.3.9: ![image](https://private-user-images.githubusercontent.com/884277/364973566-b7890ecb-a40d-4fd1-afbb-fd7e1fe9ca77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NzY2MDUsIm5iZiI6MTcyNTU3NjMwNSwicGF0aCI6Ii84ODQyNzcvMzY0OTczNTY2LWI3ODkwZWNiLWE0MGQtNGZkMS1hZmJiLWZkN2UxZmU5Y2E3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQyMjQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDczNzUyNjY0YTc0NTExMmYyYmMyZDgyMzA0NzUwOTZkY2RjMTlmMzg5NWMzZmQ4MjZlMmU0ODBmMzFmYzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lBlCijTAHlCpYDRg0lc64X4ZtKQEocGj0T5TCKBIS9w) It's working at least since 2016 [qbittorrent/qBittorrent#5995](https://github.com/qbittorrent/qBittorrent/issues/5995)

I think that's more of the fact that there is a / and its not sanitized - and just results in a child directory, not that it's exactly a sub-category.

Either way, given our tendency to emphasize the value of linking with v6, I'm not entirely sure where subcategories would come into play unless you had linking disabled.

I'm not a qbittorrent user, but would be curious what you thought the use-case would be for such a thing, especially given that they would like return with the slash (i'd assume) and then just append the normal .cross-seed? Is that the behavior you would be desiring? Or are you just commenting to clarify?

**Comment by NLZ** [comment]
I think it's an intentional design and not the lack of sanitation, given that it is programmed to create the sub-directories as well.

It would work exactly how non-flat linking works in v6 right now, but instead of AutoTMM disabled and explicit save path defined for the tracker, it would define sub-categorizes for each tracker and would allow AutoTMM to work. Not sure if duplicateCategories should be considered with flatLinking disabled, afaik it doesn't make much sense.

But admittedly for hardlinked files the AutoTMM is not that useful, given that moving to a different drive would break the hardlinks, so I think we can consider this just a clarification.

**Comment by zakkarry** [comment]
With linking enabled duplicateCategories only affects the tags.

I'm not sure about this implementation, but it makes a bit of sense how you're describing it, however it does present the issue of users on pre 4.6 (or whenever subcats were introduced to the UI) potentially not wanting to use this.

I don't really touch qbittorrent to this respect, so it would be a team decision on whether to support it and likely something that @ShanaryS would be in charge of, given that he's the qbittorrent user on the dev team.

Curious as to what his thoughts are and any pitfalls that may come from doing things this way.

**Comment by ShanaryS** [comment]
This can be done, but `cross-seed` will still disable autoTMM for simplicity. But lots of users won't benefit from this since it's new and lots of alternative webuis don't support it either.

It would be a cosmetic thing but the user would be able to enable autoTMM if they need it.
