### ISSUE TITLE
Deluge API is temperamental resulting in incorrectly `skipping incomplete torrent` 

### ISSUE THREAD

**Issue by RogueOneEcho** [cross-seed/cross-seed#711]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

When executing a search with cross-seed using **deluge** the logs are filled with warnings of `skipping incomplete torrent` despite these torrents being 100% downloaded and seeding.

This occurs for both `v5.9.2` and `v6.0.0-10`.

### Reproducing the bug

Following these steps to manually [inspect the deluge API response with CURL](https://deluge.readthedocs.io/en/latest/devguide/how-to/curl-jsonrpc.html)

```bash
curl -d '{"method": "web.update_ui", "params": [["state", "progress", "save_path", "label"], {"hash": "**TORRENT HASH**"}], "id": 1}' -K curl.cfg | jq '.result.torrents'
```

Shows the  API  will occasionally response with `state` and `progress` omitted.

```json
{
  "**TORRENT HASH**": {
    "save_path": "**PATH**",
    "label": "**LABEL**"
  }
}
```

Repeating the request will eventually respond:

```json
{
  "**TORRENT HASH**": {
    "save_path": "**PATH**",
    "label": "**LABEL**",
    "state": "Seeding",
    "progress": 100
  }
}
```

As these fields are absent this causes cross-seed to assume the torrent is incomplete.

https://github.com/cross-seed/cross-seed/blob/0ab8741a5fdbab23db8c743d6ba8a6152ae2c460/src/clients/Deluge.ts#L470-L471

### What should be happening?

I would suggest that if those fields are absent from the response then cross-seed could attempt to retry the API request a few times, if still no luck then it should report "unable to torrent status" or similar which would be more accurate than incorrectly warning `skipping incomplete torrent`

### Your setup

```markdown
- OS: Ubuntu 20.04 LTS
- Docker: Yes (ghcr.io/cross-seed/cross-seed:master)
- Deluge: v2.1.1 https://fleet.linuxserver.io/image?name=linuxserver/deluge
```

### config.js (REDACT SENSITIVE INFORMATION)

N/A

### verbose logs

No additional verbose logs other than repetitions of:

2024-06-10 14:25:08 warn: Found **TORRENT NAME** [**HASH**...] on **TRACKER** by MATCH from torrentDir (**NAME** [**HASH**...]) - skipping incomplete torrent

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
This is a known issue I have faced with docker containers, particularly with large amounts of torrents. I've looked into it a fair amount and discussed with one of the active developers on Deluge's team (I am a moderator on their support forums and wrote the Deluge integration in cross-seed).

The solution I've come up with is that you can disconnect the web daemon (it is an entirely separate process and appears to be getting desync'd somehow) from the RPC daemon, and reconnect it and the instance will act normally for some time.

I, myself, have a script scheduled to disconnect and reconnect the web daemon every couple of days. This usually is only a problem with older torrents, so if you're doing a full search or something you may run into it. I haven't seen it crop up many times during completion script calls.

It does seem to only affect containers, though, given that they have separate web and daemon processes.

**Comment by zakkarry** [comment]
> ```shell
>  [
> ```

We use update_ui with specified keys, so it only returns exactly what we need. If you do not specify keys, it returns everything.

**Comment by zakkarry** [comment]
My current thought is that if the keys are missing from the response, I could reconnect the web daemon and retry...however I'm not sure how this interaction could possibly backfire.

My initial concern would be in the rare case that there are multiple instances in the web daemon config, although this would be extremely rare and I doubt would ever actual cause problems. Currently on startup, if the web daemon is disconnected from the deluge daemon, it will automatically connect it to the first entry, which is going to be the only one in 99.9999% of cases.

@mmgoodnow might have some thoughts on this, as I've discussed this issue with him previously.

**Comment by mmgoodnow** [comment]
Can we just get the root cause issue fixed?

**Comment by zakkarry** [comment]
Cas isn't really that active for personal reasons. He currently devotes only a day or two per month to actual development on Deluge. The other dev, who I've spoken about this with wasn't really sure where the problem was sourced from, but I was able to determine that it seems to be present only where the web daemon and client daemon are separated, although I can't be sure this is the case, I've never seen it in standalone mode where the two are combined.

I can only speculate since my architectural knowledge outside of the API itself is somewhat limited. I've already messaged one of the devs with this issue link, although I'm not entirely sure how quickly it would get to stable either way.

It is not a cross-seed issue, as I said this presents itself in the webui itself as well as occasionally in the thin client. You will see NaN% or blank names.

I'm convinced it has something to do with deluge's caching of the torrent list, but I have only speculation to base this off.

**Comment by zakkarry** [comment]
To clarify, I've only ever seen this in Docker implementations. Both binhex and lsio containers are affected, as well as my personal develop branch container I maintain.

Docker is generally the most common implementation of the processes being ran seperately.

**Comment by mmgoodnow** [comment]
@zakary do you know where the code lives for the web daemon and client daemon? I could poke through the code and see if I can find anything. 

Would it be possible to write a docker image that runs them together rather than separate?

**Comment by zakkarry** [comment]
>Repeating the request will eventually respond:

How many times would you expect to need to repeat this request before the problem appears, I only ever encountered it "by chance" and I may have a solution - but finding this "in the wild" is not ideal.

If you could give me like, an interval and number of times repeated before you reliably saw _SOME_ problem, that would be helpful.

**Comment by zakkarry** [comment]
I may have a better solution, but I need the information about timeframes to replicate....right now I'm just sitting here waiting to see if it happens with my scripts turned off.

I'd rather find a valid solution than a workaround, but if this doesn't work that may be how we go.

Yes there is a way to see which host it is connected to.

**Comment by zakkarry** [comment]
I just did the curl with no hash key, its been ~18hr since I switched to what I think may fix the issue.

I haven't approached binhex or any lsio maintainers about this yet, I don't think it's particularly ideal of a solution for them, but it may be the solution that's necessary. 

If you'd like to also try this to double our reproduction surface, feel free to hop on the discord and I can explain it to you, my name is zakary in our server.

If you don't have discord I can at some point today write out some basic instructions. I think based on our conversation here you'd be able to get it working in the same manner I am testing fairly easily.

Either way, I'll continue to monitor what I'm trying right now.

**Comment by zakkarry** [comment]
Also of note, with the connection (session_id) connected, you should not use the same `id` value repeatedly.

It does not have to be incremental, and it does not have to be anything particular, just a number and different.

**Comment by zakkarry** [comment]
After you login, you can use the following command to see if any of the state or progress values are missing from your entire list.

```bash 
curl -d '{"method": "web.update_ui", "params": [["state", "progress", "save_path", "label", "name", "total_remaining"], {}], "id": 3}' -K curl.cfg | jq '.result.torrents | to_entries | map(select(.value.state == null or .value.progress == null)) | from_entries'
```

add an `or .value.whatever == null` as you desire to find other missing values.

I've opened a PR to maybe "help" with the issue, although depending on what I've dubbed a desynchronization it may not entirely fix the problem. So far I've not found an issue - going on 24hr.

**Comment by zakkarry** [comment]
Just a note, this commit in the latest pre-release has the potential to help, although doubt it will 100% eliminate the possibility by itself.

**Comment by zakkarry** [comment]
It has to do with the container itself and Deluge and the WebUI - the commit I made is sort of an attempt to improve the situation as best I can in the interim.

Something I've found over the last 8 or so months I've been aware of this is that it tended to be older torrents that got less traffic, and thus received fewer `torrents_status_update()` calls....repeatedly hitting it with requests is going to do nothing but prolong the time it takes to reproduce - if it even will (just my experience though, yours may differ).

I tend to check every 3-6 hours right now. I'll probably extend that to every 8-12 if it doesn't happen within a day or two now.

Restarting the container and reconnecting the webUI to the daemon also "resets" (only term I know for this) the process....so don't do those either if you're trying to replicate it.

If you use IRC, I'm also on frequently and can meet you on a neutral server like freenode or efnet or something.

**Comment by zakkarry** [comment]
I'm curious if that could indeed be the case, in which case I do how a solution could be implemented...however I'm not entirely sure this solves it as I also have a script that sorts my labels and pulls the entire list every 15m.

I've never just run them independently without the other (my disconnecting/reconnecting script) - so I'm not sure if one or the other independently solves this.

I'm still exploring this, but if this is a "solution" of sorts - then that would be good.

**Comment by zakkarry** [comment]
So I've concluded that running the webui plugin as opposed to the web daemon itself (separate deluge-web process) or the fact that I'm pulling the entire torrent list somewhat regularly (every 15-30m for a script) - prevents this.

I have not been able to once replicate this yet during my testing the last ~10 days, and I'm not sure which solved it or if its just being temperamental about being temperamental.

I'm tempted see switch back to the web daemon and see if it presents itself.

Any update on your end?

**Comment by zakkarry** [comment]
> I restarted the VM and deluge container about 10 hours ago and now I have a large number of torrents - 30% - in a state of desync. The `web.update_ui` request for these torrents doesn't have the `state` or `progress` keys but it does have `"total_remaining": 0` so #715 probably does fix the issue.
> 

Yep, looks about right for what ive seen. Also seen name go missing, as well as label.

Would you be able to get deluge to use the webui plugin instead of the daemon and test if this persists?

**Comment by zakkarry** [comment]
Well if checking a box in a client and fixing all your problems isn't stable enough I'm not sure what is... Mine's been running 11d with no sign of a problem.

Up to you though.

Running deluge-web separately from the main deluge core daemon is a bit of a docker-specific implementation. I'm not sure why it was chosen as such for the containers, but there isn't any real reason I'm aware of to do this specifically over the plugin, and no drawbacks to switching to one over the other functionally.

**Comment by mmgoodnow** [comment]
I dug into this from the Deluge side and there appear to be **two related bugs** in Deluge that can both produce the kind of partial status payloads shown in this issue.

## Short version

Deluge can return **partial status objects** when it thinks it is sending only a diff instead of a full status payload.

There are two places where that can go wrong:

1. **In deluge-web (`SessionProxy`)**
   - `web.get_torrent_status` and `web.update_ui` go through a cache layer called `SessionProxy`.
   - That cache was sometimes asking the core for a **diff** even when it did not already have all of the requested fields locally.
   - If the core replied with only a partial diff, `SessionProxy` could keep serving incomplete results until the web daemon reconnected.

2. **In the Deluge core diff logic**
   - The core keeps a per-session "last status" baseline for diff requests.
   - But that baseline currently changes depending on which fields were requested last.
   - So if one request asks for a **small set of fields**, and a later request asks for a **larger set**, the later request can come back with only the "new" fields from that larger set instead of the full status the caller expects.

So the core problem is basically: **Deluge's diff/partial-update behavior is not stable when the requested keyset changes over time.**

That lines up well with the reports here that things can look fine for a while, then go bad for a long-lived web session, and then recover on reconnect.

## Repro that should reliably poison a fresh deluge-web session

A single request does not do it. The reliable repro is:

- start with a **fresh** deluge-web -> deluged connection
- prime the core diff baseline with a **direct `core.*` call** using a narrower keyset
- then hit the same torrent through **`web.*`**, which goes through `SessionProxy`

I would also keep any normal web UI tab closed while testing, so the grid polling does not interfere with the session state.

```sh
URL='http://127.0.0.1:8112/json'
COOKIES='/tmp/deluge-web.cookies'
PASSWORD='your-web-password'
HASH='target-torrent-hash'

rpc() {
  curl -sS \
    -b "$COOKIES" -c "$COOKIES" \
    -H 'Content-Type: application/json' \
    "$URL" \
    -d "$1"
}

# 1. login
rpc '{"method":"auth.login","params":["'"$PASSWORD"'"],"id":1}'

# 2. get host id
rpc '{"method":"web.get_hosts","params":[],"id":2}'
# pick the first host_id from result[0][0]
HOST_ID='paste-host-id-here'

# 3. force a fresh web->core session
rpc '{"method":"web.disconnect","params":[],"id":3}'
rpc '{"method":"web.connect","params":["'"$HOST_ID"'"],"id":4}'

# 4. prime the core diff baseline directly, bypassing SessionProxy
rpc '{"method":"core.get_torrent_status","params":["'"$HASH"'",["state","progress"],true],"id":5}'

# 5a. read via SessionProxy
rpc '{"method":"web.get_torrent_status","params":["'"$HASH"'",["state","progress","save_path","label"]],"id":6}'

# 5b. closer to the cross-seed/web.update_ui shape
rpc '{"method":"web.update_ui","params":[["state","progress","save_path","label"],{"hash":"'"$HASH"'"}],"id":7}'
```

On buggy Deluge, step `6` or `7` can come back missing `state` / `progress`, often with only something like:

```json
{
  "<hash>": {
    "save_path": "...",
    "label": "..."
  }
}
```

And reconnecting deluge-web to the daemon clears it, because that resets the web->core RPC session.

If this can reliably poison a fresh session with the sequence above and then clear it with `web.disconnect` / `web.connect`, that would be strong evidence that the bug we found is the same bug behind at least one class of failures in this issue.

## Cross-seed workaround: use `core.*` instead of `web.*`

If cross-seed wants a mitigation without waiting on a Deluge fix, it can keep using Deluge Web's HTTP `/json` endpoint **but call `core.*` methods instead of `web.*` methods**.

Specifically:

- instead of `web.get_torrent_status(...)`, use `core.get_torrent_status(...)`
- instead of `web.update_ui(...)`, use `core.get_torrents_status(filter, keys, false)`

That bypasses `SessionProxy`, which is where the web-side cache bug lives.

Important caveat: if cross-seed uses `core.*` with **`diff=true`**, it can still hit the core-side bug. So the safe mitigation is:

- use `core.get_torrent_status` / `core.get_torrents_status`
- pass **`diff=false`**
- request the exact keys cross-seed needs

## Deluge-side fixes

I put together two Deluge draft PRs that address the problem from both sides:

- [mmgoodnow/deluge#1](https://github.com/mmgoodnow/deluge/pull/1) — fixes the **web / `SessionProxy` side**
  - `SessionProxy` now falls back to a full fetch when its local cache is missing requested keys, instead of trusting diffs to fill gaps.
  - This addresses the web-side partial-update bug.

- [mmgoodnow/deluge#2](https://github.com/mmgoodnow/deluge/pull/2) — fixes the **core diff-baseline semantics**
  - the core now preserves per-session diff baselines across changing keysets instead of replacing them with each narrower/wider projection.
  - This addresses the underlying keyset widening/narrowing instability in `diff=True`.

My current take is that these should probably **coexist**:

- `#2` makes the core diff API safer for everyone
- `#1` makes `SessionProxy` robust even if its own local cache is incomplete for some reason

**Comment by zakkarry** [comment]
@mmgoodnow do you mind if I take some time to review these issues, and also add in some of my local handling of the desync bugs to prevent the need for useClientTorrents to be omitted from Deluge clients? As I discussed in the email I sent to you just earlier this evening?



Edit:
I was also curious about whether or not we could keep some sort of torrent client cache local, where when we update it only overwrites if anything has changed while keeping the things that havent. This could prevent the desync from having as much of a negative effect pending the daemon reconnecting and also increase the performance since Deluge's JSON-RPC can be rather slow at large torrent count. I'd assume this could also benefit other clients as well.

**Comment by RogueOneEcho** [comment]
> I was also curious about whether or not we could keep some sort of torrent client cache local

This is definitely worth considering. qui does something similar for qBittorrent and even exposes it as a reverse proxy/cache wrapper for the API itself providing a substantially quicker response times. My non-scientific test for `/torrents/info` showed 375 ms via qui vs 2400ms response from qBit itself.

 https://getqui.com/docs/features/reverse-proxy/#read-operations-served-from-qui

**Comment by ShanaryS** [comment]
The problem with caching the torrents for `cross-seed` is that it doesn't offer much benefit. `qui` has the cache as they need it in general to serve an alternate UI. What I imagine they are doing since they control the qBittorrent install with their container is a script that runs on torrent add so they are always in sync, but we can't do that with `cross-seed` without asking the users to. We would need this (and something similar for all clients) in order to use caching for `announce`, `rss`, `search`, and `inject`. There is no way to trigger on deletion for qBittorrent though, but that doesn't matter as we can just reject later in the process. We need to poll the torrent again right before injecting to make sure that the save paths are the most up to date to ensure linking works properly.

Since `announce` and `rss` deals with new uploads, we need it to be the most up to date. If a torrent is announced 2s apart, the first one might get added to client by the arrs and then `cross-seed` will save the second for injection by seeing the first one was just added and is incomplete. For `search` and `inject` they could use the cache but they only run once per day or once per hour, which is likely longer than any cache refresh time that would be used.

Using the cache in case of connection drops is fine though, but not for any jobs if the api is available.

**Comment by zakkarry** [comment]
I dont mean that the cache is the primary, but when (with deluge) we run through things and there are missing bits of information (typically the status/seeding/state and sometimes the name) - it could provide useful to have the cache as a fallback, not as primary.

I think we should still be updating it as we normally would, just when things fail - prior to the reconnecting I plan to open a PR for here in a few hours, it would provide _SOMETHING_ to go off of....
