### ISSUE TITLE
Invalid config `searchCadence must be at least 1 day`

### ISSUE THREAD

**Issue by RogueOneEcho** [cross-seed/cross-seed#752]
### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### What's happening surrounding the bug? (context)

I upgraded to v6.0.0-24 from v6.0.0-10 and my config is now showing as invalid.

According to the docs 
> There is a minimum of 1 day unless [excludeRecentSearch](https://www.cross-seed.org/docs/basics/options#excluderecentsearch) has been set.
https://www.cross-seed.org/docs/basics/options#searchcadence

However I have have `excludeRecentSearch: "30d"` but it's still showing an error:

```
2024-07-19 20:32:15 error: Option: searchCadence
				searchCadence must be at least 1 day.
				(https://www.cross-seed.org/docs/basics/options#searchcadence)
```
 "https://www.cross-seed.org/docs/basics/options#searchcadence"

### Reproducing the bug

```json
excludeRecentSearch: "30d",
searchCadence: "6h"
```

### What should be happening?

Config should be accepted.

Feel free to show a warning if you consider it not an ideal setup but it's a misuse of error as it's a valid use case.

### Your setup

```markdown
- OS: Ubuntu
- Prowlarr/Jackett: N/A
- Docker: Yes
- Misc:
```

### config.js (REDACT SENSITIVE INFORMATION)

```json
excludeRecentSearch: "30d",
searchCadence: "6h"
```

### verbose logs

```
cross-seed  | 2024-07-19 21:13:28 info: cross-seed v6.0.0-24
cross-seed  | 2024-07-19 21:13:28 info: Validating your configuration...
cross-seed  | 2024-07-19 21:13:28 warn: includeSingleEpisodes is not recommended when using rss or announce, please read: https://www.cross-seed.org/docs/v6-migration#updated-includesingleepisodes-behavior
cross-seed  | 2024-07-19 21:13:29 error: Option: searchCadence
cross-seed  | 				searchCadence must be at least 1 day.
cross-seed  | 				(https://www.cross-seed.org/docs/basics/options#searchcadence)
cross-seed  | 
cross-seed  | 2024-07-19 21:13:29 error: Configuration:
cross-seed  | 				excludeOlder and excludeRecentSearch must be defined for searching. excludeOlder must be 2-5x excludeRecentSearch.
cross-seed  | 				(https://www.cross-seed.org/docs/basics/options)
cross-seed  | 
cross-seed  | 2024-07-19 21:13:29 error: Your configuration is invalid, please see the errors above for details.
cross-seed exited with code 1
```

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
So you came to the discord, and read the docs? You acknowledged that you did this, yet I don't see you having asked anything there.

Read the note in the doc's for the migration guide.

https://www.cross-seed.org/docs/v6-migration#stricter-configjs-validation

**Comment by ShanaryS** [comment]
Why do you need `6h` instead of `1d`?

**Comment by zakkarry** [comment]
For pre-release of v6, the regular docs are not the primary source. The entire page for v6 migration is.

**Comment by zakkarry** [comment]
![image](https://github.com/user-attachments/assets/9e755d37-b84a-42e9-be4f-47858b4d955b)
We ask this for a reason, please do not ignore this in the future and check this box if you have not done this.

**Comment by zakkarry** [comment]
If you have some valid use case for 6h, feel free to let us know and we may consider it, as the note on the documentation suggests you do.
> If you encounter problems with these restrictions which you feel are invalid, please reach out to us on [Discord](https://discord.gg/jpbUFzS5Wb) to discuss this further.

Otherwise, you will need to adjust your workflow and configuration.

**Comment by zakkarry** [comment]
We try to keep issues to actual bugs and feature requests and the like, breaking changes are to be expected with pre-release process, however what we are asking is more or less what necessitates such an aggressive and frequent searchCadence.

The reason I ask is because we can't always consider every single setup, but in almost every case what has ended up happening is that the user can achieve the same or better manner with a more reasonable configuration.

Feel free to have a conversation with us here, if you'd like. This was introduced in -24 - so you don't have to strictly stick to -10, -23 would work, and there are a variety of other features you'd be missing out on going to -10.

Are you not using rssCadence or anything?

**Comment by ShanaryS** [comment]
What is your goal here? How do you still see this as a "validation error"?

You have not given a reason why you need `6h`. We actually discussed this as the minimum before release but couldn't find any benefits over `1d`. But you seem to have a very strong one enough to ignore critical updates?

**Comment by zakkarry** [comment]
>I know it's considered a pre-release version but I'm confident in its stability, therefore I don't anticipate there being any critical updates. 

There have been a dozen releases since -11, we aren't just making random releases for no reason - just so you know.

>My interpretation of the question was it was an or statement:

A deliberate error stating that there is a problem that explicitly stated requirements for configuration have changed and, honestly, that is kind of a stretch to really be deemed a bug. We made a conscious decision, hence the error stating as much.

>I'm then informed that the documentation I referred to isn't relevant and instead I should have full knowledge of the 3500 word article on migrating to v6.

Yes, the v6 migration guide is the relevant v6 documentation. It is not "released" - and therefore the remainder of the documentation is not updated in its entirety to reflect all the changes yet. Most of our userbase is still on v5.

>I'm then informed that this isn't a bug, that I should have known this wasn't a bug and therefore it's a support request which should have been filed on discord.

Deliberate messaging and errors are all consistently showing that this was a conscious decision, as I stated before. 

I've updated the issue template. 

You could have also put support requests in "Discussions" in Q&A if you wanted. It's not a bug. It's a development decision you did not like, and while I understand your desire to "do what you want" - we are also making decisions to do what we think is best overall. If you intend to try and convince us that your preference is valid and "better" for you, we want to know why. Since you refused to give context for why you need those settings, it was kind of a non-starter.

>I'm again informed I should have gone to Discord. Or I should just accept that decisions the maintainers have made, adapt my setup to follow their and not dare question it. [slightly overdramatised but that was my interpretation at the time]

Jesus.

>The question "I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue" should be rewritten or removed. When creating an issue I already identified I considered this a bug, so this check box is unnecessary.

It's been rewritten, but the ability for you to "interpret" things you don't agree with as a bug when it's pretty clearly a decision - that's not something that language can fix.

>Consider redirecting users for support to GitHub discussions https://github.com/cross-seed/cross-seed/discussions in addition to Discord. This is very much personal opinion but I don't find Discord productive, whereas GitHub discussion seems to be setup for this exact use case (separating bug reports from support).

Already done, as I said.

<hr>

Since you seem to have an issue with me, I'll bow out and you can continue this conversation without me.

**Comment by ShanaryS** [comment]
> I don't really follow why I need to justify how I use open source software on my own machine, connecting to my own accounts?

Of course you are free to pin versions or fork and make changes, that's perfectly acceptable. We would just prefer hearing the reasons first so we can decide if we will address it. We only restrict users when there is no value to gain by deviating while possible causing harm.

> I'm confident in its stability, therefore I don't anticipate there being any critical updates

I'm not saying there could be a critical update, I'm saying that `v6.0.0-24` is. The new caching behavior is one of the biggest improvements of v6. I was simply confused how you had such a strong reason skip it yet refused to state it.

> What is wrong with having a `searchCadence` of `6h` instead of `24h`?

When searches are started, it can be very intensive on your disk, even if nothing will be searched. This is because it needs to index everything and perform tons of checks and validation on every torrent file or data file. So we limit to `1d` to minimize this small but unnecessary added stress on your drives. It also creates tons of logging which makes the log files extremely bloated.

All this could be ignored if there was value to going less than `1d`, which brings me to:

> I have quite a few trackers configured and they aren't all particularly reliable so often connections fail. By running the search four times per day it means a search that failed to connect earlier is re-run

Search is not for getting cross seeds as fast as possible, that is for rss/announce/webhook which is far less strenuous on your system and trackers. This is a temporary problem you are having, everything will get searched eventually. Long term `1d` will be sufficient which is what it's designed for.

> I really don't follow how `excludeRecentSearch` and `excludeOlder` are linked at all? How can age have a MAX value?! Why is `excludeOlder` required at all?

This is so that searches are only performed a set number of times, a maximum of `6x`. In reality, searches only need to happen once for the lifetime of `cross-seed`, rss/announce will catch all future releases. RSS pagination will be added soon so `cross-seed` downtime will not miss any releases.

> I'm using cross-seed because I want to cross seed as much as possible, I don't follow why you'd only want to cross-seed new content?

This is exactly why these restrictions were added. You do not fully grasp how the entire application functions together and are likely to have harmful configurations. As I said earlier, we would have not restricted it if it brought any value. Of course we would make changes though if a user brought valid use case we haven't considered.

> The complexity of the constraint is a strong sign it's too complex

These constraints ensures this only happens in daemon mode, this "complexity" gives you flexibility. You can bypass these restrictions as the PR says.

I also disagree with your assessment of the responses, they were appropriate as zakary noted above.

**Comment by mmgoodnow** [comment]
It's understandable that you interpreted this as a bug. When the program and the documentation it links to don't agree, _something_ has a bug. In this case, v6 is on prerelease, so these links aren't accurate any more. We could consider versioned documentation, but I'd also like to get us out of prerelease soon. (We've been on prerelease for longer than I anticipated, which has made this problem worse.)

It sounds like we've already captured an action item out of this conversation, which is to offer GitHub Discussions as an alternative to Discord. Thank you for continuing to engage with us and keeping the conversation productive.

> I don't really follow why I need to justify how I use open source software on my own machine, connecting to my own accounts?

Yes—as the account holder on your trackers, you are responsible for how you use `cross-seed`, and you are also free to fork or modify the code in any way. However, as `cross-seed`'s user base has grown, every change or decision we make as developers has a larger impact than in the past, and we have to take some responsibility too. 

To that end, `cross-seed` v6 has become much more opinionated about users' configurations, and some of them are no longer valid. In hindsight, it would have been good to do this from the beginning, but we were able to benefit from an experimentation period where users were able to figure out the "good" settings.

Remember, we want to find all the cross-seeds too—we believe in the efficacy of v6, regardless of the new restrictions on configuration. If you want to find old cross-seeds, you can set excludeRecentSearch and excludeOlder to high numbers - `1 year` and `5 years` is what I'm using.
