### ISSUE TITLE
error: qBittorrent login failed: fetch failed

### ISSUE THREAD

**Issue by Snake883** [cross-seed/cross-seed#837]
### What's happening surrounding the bug? (context)

```
# docker start -a 4a1d7841c258
Configuration file already exists.
2024-12-09 10:28:10 info: cross-seed v6.1.1
2024-12-09 10:28:10 info: Validating your configuration...
2024-12-09 10:28:10 warn: If using Automatic Torrent Management in qBittorrent, please read: https://www.cross-seed.org/docs/v6-migration#qbittorrent
2024-12-09 10:28:13 error: qBittorrent login failed: fetch failed
```
The Cross-Seed docker container is not accessible via console.

I suspect the problem could be releated to QBT/system being really slow, and not responding fast enough (QBT doesn't perform very fast for me when I have 1000's of torrents).

### Have you checked for any existing open/closed tickets that are the same or similar to your issue?

- [X] I've searched far and wide!

### I have gone to the Discord server for support and/or acknowledge that this is a bug and not a support issue

- [X] I've tried to solve this already

### Reproducing the bug

1)  Error appears when starting docker container.

### What should be happening?

Cross-Seed should be able to access qBittorrent.

Perhaps a configuration setting to increase the login timeout?

### Your setup

```markdown
- OS: Unraid
- Docker: Docker
- Repository: crossseed/cross-seed
```

### config.js (REDACT SENSITIVE INFORMATION)

```

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
module.exports = {
    delay: 30,
    torznab: [REDACTED],	
	dataDirs: ["/data/torrents/movies","/data/torrents/tv"],
    matchMode: "safe",
	dataCategory: "cross-seed-data",
	linkDir: "/data/torrents/links",
    linkType: "hardlink",
    skipRecheck: false,
    maxDataDepth: 2,
    torrentDir: "/torrents",
	outputDir: "/cross-seeds",
    includeEpisodes: false,
    includeSingleEpisodes: false,
    includeNonVideos: false,
    fuzzySizeThreshold: 0.02,
	excludeOlder: "15 weeks",
	excludeRecentSearch: "3 weeks",
	action: "inject",
    rtorrentRpcUrl: undefined,
	qbittorrentUrl: "http://[REDACTED]:[REDACTED]@192.168.1.37:8080",
    transmissionRpcUrl: undefined,
    delugeRpcUrl: undefined,
	duplicateCategories: true,
    notificationWebhookUrl: undefined,
    port: 2468,
    host: undefined,
    apiAuth: true,
	rssCadence: "10 minutes",
	searchCadence: "1 week",
    snatchTimeout: undefined,
	searchTimeout: "90 seconds",
    searchLimit: undefined,
};
```

### verbose logs

```
Configuration file already exists.
2024-12-09 09:34:33 info: cross-seed v6.1.1
2024-12-09 09:34:33 info: Validating your configuration...
2024-12-09 09:34:33 warn: If using Automatic Torrent Management in qBittorrent, please read: https://www.cross-seed.org/docs/v6-migration#qbittorrent
2024-12-09 09:34:36 error: qBittorrent login failed: fetch failed
```

### Failure or refusal to provide the information we require to address bugs will result in potential closure of the issue.

- [X] I acknowledge that i have searched existing issues, read the documentation and faq, read the logs to see if the answer was provided in error messaging, and attempted to get support via the Discord prior to submitting this issue.

**Comment by zakkarry** [comment]
You said/checked that you came to seek support from Discord or other means already, and I do not see any threads there or attempts to seek support that show more context than this.

Also, your particular setup or configuration is not unique in the sense of having thousands of torrents, and the API of qBittorrent does not experience the same extreme delays/responsiveness problems as the WebUI might.

Based on experience, this is probably something to do with you using a VPN with qBittorrent, but since you gave zero details on your qBittorrent setup I can't say for sure.

https://www.cross-seed.org/docs/basics/faq-troubleshooting#i-cant-reach-my-prowlarrjackettcross-seedtorrent-client-using-dockervpn

In addition, just as a note, you might do well to read https://www.cross-seed.org/docs/v6-migration#data-based-matching-use-cases because it appears you've also decided to use dataDirs without mentioning usenet usage of any sort.

Please seek support before opening bug reports for configuration and networking issues.

**Comment by Snake883** [comment]
> Please seek support before opening bug reports for configuration and networking issues.

Will do next time.  Thank you.

**Comment by Snake883** [comment]
Solution:

Restarting the Unraid docker service appears to have solve the issue.
